import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { navItems } from "@/components/Navbar/menu-list";
import { MainNavbar } from "@/components/Navbar/main-navbar";
import { ThemeProvider } from "@/components/theme-provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="tr" suppressHydrationWarning>
      <body className="antialiased">
        <ThemeProvider>
          {/* Navbar server component olarak */}
          <MainNavbar navItems={navItems} />

          {/* Sayfa içeriği navbar dışında */}
          <main className="mt-[80px]">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
